plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id "org.openapi.generator" version "7.12.0"
}

openApiGenerate {
    generatorName.set("java")
    inputSpec.set("$projectDir/src/main/resources/api-spec.yaml")
    outputDir.set("$projectDir/build/generated")
    modelPackage.set("ru.yandex.shop.window.demo.client.model")
    apiPackage.set("ru.yandex.shop.window.demo.client.api")
    configOptions.set([
            sourceFolder: "src/gen/java/main/codegen",
            interfaceOnly: "false",
            library: "webclient",
            useTags: "true"
    ])
}

tasks.named("compileJava") {
    dependsOn(tasks.named("openApiGenerate"))
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'io.r2dbc:r2dbc-h2'
    implementation 'org.openapitools:jackson-databind-nullable:0.2.4'
    runtimeOnly 'com.h2database:h2'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.0'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.github.codemonstur:embedded-redis:1.4.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/src/gen/java/main/codegen"
        }
    }
}

tasks.withType(Jar) {
    manifest {
        attributes['Main-Class'] = 'ru.yandex.shop.window.demo.ShopWindowDemoApplication'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}