openapi: 3.0.3
info:
  title: Payment API
  version: 1.0.0
  description: API для обработки платежей

paths:
  /api/payment:
    post:
      tags:
        - Payment
      summary: Обработка платежа
      operationId: processPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Платеж обработан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Недостаточно средств
  /api/payment/{username}:
    get:
      tags:
        - Payment
      summary: Проверка баланса
      operationId: getBalance
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Баланс получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '404':
          description: Нет баланса для данного пользователя
components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - userName
        - amount
      properties:
        userName:
          type: string
          example: John
        amount:
          type: string
          format: decimal
          example: 100.99
    PaymentResponse:
      type: object
      properties:
        success:
          type: boolean
        updatedBalance:
          type: string
          format: decimal
    BalanceResponse:
      type: object
      properties:
        userId:
          type: string
          example: 1
        balance:
          type: string
          format: decimal
          example: 100.23