spring:
  r2dbc:
    url: r2dbc:h2:mem:///practicum?;B_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  web:
    resources:
      static-locations: classpath:/static/, file:uploads/
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    io.r2dbc: DEBUG