spring:
  r2dbc:
    url: r2dbc:h2:mem:///practicum?;B_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  web:
    resources:
      static-locations: classpath:/static/, file:uploads/
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: product-service-client
            client-secret: dCl2PLhehZfSvGgeBEPzegl0R5Fpgmi8
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
          payment-service-client:
            client-id: payment-service-client
            client-secret: KNm0PqYh64gbfYnaWqf4uYtsyaumtMiE
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/shop
            token-uri: http://localhost:8083/realms/shop/protocol/openid-connect/token
logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    io.r2dbc: DEBUG